Postman collection tutorial
amadeus4dev/developer-guides pull request #123
Opened 2023-02-09 21:06 UTC by nicoongit

2023-02-10 09:03 UTC, minjikarin commented
Thanks Nico! :D 
I have 2 comments 

- API keys : the API keys need to be input in 'environment' not in the individual request such as authorization. the details is here https://developers.amadeus.com/blog/how-to-play-with-self-service-apis-with-no-code-using-postman 
- at the end of page, can we also highlights that we have 'senarios' folder under 'air' and 'hotel' to illustrate better for flight booking engine flow + hotel booking engine flow. users doesn't need to copy & paste their response to request the next step.

2023-02-10 09:05 UTC, minjikarin requested changes

2023-02-10 09:05 UTC, minjikarin commented on docs/programming/postman.md
> +## Generate the access token
-> APIs key to be in 'environment'

2023-02-10 09:47 UTC, tsolakoua commented
- I would suggest the authorization part to update it the same way that is in the [article](https://developers.amadeus.com/blog/how-to-play-with-self-service-apis-with-no-code-using-postman) from the sections `Configuring the environment` and `Get the access token`. What we actually do is we write small script so the access token will be passed automatically to the header of each API call. 
- Can we also show an actual API call of a specific API such as in the section `Calling Amadeus Self-Service APIs` of the blog? 
- Also, instead of showing only the JSON response, can we also show the visualization? For example if you call the Safe Place API you see also:
![Screenshot 2023-02-10 at 10 45 15](https://user-images.githubusercontent.com/15012967/218059066-d175ddfc-a654-464c-97ac-4d4a566a4fc1.png)

2023-02-10 15:50 UTC, nicoongit commented
Thanks @minjikarin , @tsolakoua  for the feedback. I believe I've addressed the comments, can you please check?

2023-02-10 16:19 UTC, minjikarin approved these changes

2023-02-11 08:32 UTC, tsolakoua approved these changes

2023-02-11 08:32 UTC, merged